# Stage 1: Build the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy solution file and project files
COPY *.sln ./
COPY AuthenticationServer.Api/AuthenticationServer.Api.csproj ./AuthenticationServer.Api/
COPY gp-backend.Api/gp-backend.Api.csproj ./gp-backend.Api/
COPY gp-backend.EF/gp-backend.EF.csproj ./gp-backend.EF/
COPY gp-backend.Core/gp-backend.Core.csproj ./gp-backend.Core/

# Restore dependencies
RUN dotnet restore

# Copy the rest of the source code
COPY . .

# Build and publish the application
WORKDIR /src/authentication.api
RUN dotnet build -c Release -o /app/build
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

# Stage 2: Create the runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

# Copy the build output from the build stage
COPY --from=build /app/publish .

# Set the entry point for the application
ENTRYPOINT ["dotnet", "gp-backend.Api.dll"]